CREATE TABLE [History].[ExecForEachDBLogs]
(
[LogID] [bigint] NOT NULL IDENTITY(1, 1),
[LogTime] [datetime2] NULL CONSTRAINT [DF__ExecForEa__LogTi__2E11BAA1] DEFAULT (getdate()),
[Cmd] [varchar] (max) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'place to capture details of runs generated by sp ExecForEachDB', 'SCHEMA', N'History', 'TABLE', N'ExecForEachDBLogs', NULL, NULL
GO
