CREATE TABLE [History].[ReqDetail]
(
[TransactionDescription] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[DatabaseName] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[SignatureDateTime] [datetime2] NOT NULL,
[Operator] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[ItemKey] [varchar] (150) COLLATE Latin1_General_BIN NOT NULL,
[ComputerName] [varchar] (150) COLLATE Latin1_General_BIN NULL,
[ProgramName] [varchar] (100) COLLATE Latin1_General_BIN NOT NULL,
[ConditionName] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[AlreadyEntered] [bit] NULL,
[CONDITIONDESCRIPTION] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[CURRENTCOMPANYDATE] [date] NULL,
[CURRENTCOMPANYID] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[CURRENTCOMPANYNAME] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[CURRENTHOLDER] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[CURRENTOPERATINGSYSTEMDATE] [date] NULL,
[CURRENTOPERATINGSYSTEMTIME] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[DATEREQUISITIONRAISED] [date] NULL,
[LANGUAGECODE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[LINEVALUE] [float] NULL,
[NEWASSETCAPEX] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[NEWCAPEXNUMBER] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[NEWDUEDATE] [date] NULL,
[NEWLEDGERCODE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[NEWLINEVALUE] [float] NULL,
[NEWORDERQUANTITY] [float] NULL,
[NEWPRICE] [float] NULL,
[NEWPRODUCTCLASS] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[NEWSUPPLIER] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[OPERATORCODE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[OPERATORCURRENTGROUPCODE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[OPERATOREMAILADDRESS] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[OPERATORLOCATION] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[OPERATORNAME] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[OPERATORPRIMARYGROUPCODE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[ORIGINATOR] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[PREVIOUSCAPEXNUMBER] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[PREVIOUSDUEDATE] [date] NULL,
[PREVIOUSLEDGERCODE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[PREVIOUSLINEVALUE] [float] NULL,
[PREVIOUSORDERQUANTITY] [float] NULL,
[PREVIOUSPRICE] [float] NULL,
[PREVIOUSPRODUCTCLASS] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[PREVIOUSSUPPLIER] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[REQUISITION] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[REQUISITIONLINE] [float] NULL,
[REQUISITIONSTATUS] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[REQUISITIONUSER] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[ROUTEDTOREQUISITIONUSER] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[ROUTEDTOUSER] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[SOURCEAPPLICATION] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[STOCKCODE] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[SUPPLIER] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[WAREHOUSE] [varchar] (255) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
ALTER TABLE [History].[ReqDetail] ADD CONSTRAINT [ReqDetail_AllKeys] PRIMARY KEY NONCLUSTERED  ([DatabaseName], [SignatureDateTime], [ItemKey], [Operator], [ProgramName]) WITH (IGNORE_DUP_KEY=ON) ON [PRIMARY]
GO
