CREATE TABLE [History].[ArchiveExecForEachDBErrorLogs27OCT2016112011107]
(
[LogID] [bigint] NOT NULL IDENTITY(1, 1),
[LogTime] [datetime2] NULL CONSTRAINT [DF__ExecForEa__LogTi__2FFA0313] DEFAULT (getdate()),
[Error] [nvarchar] (2000) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'place to capture details of errors generated by sp ExecForEachDB', 'SCHEMA', N'History', 'TABLE', N'ArchiveExecForEachDBErrorLogs27OCT2016112011107', NULL, NULL
GO
